

### Users create (signup)
POST http://localhost:3000/users

Content-Type: application/json

{
  "name": "April Powers",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"
}