@jwt = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTEwMTIyNDl9.Or6-_pH1CBttlMQR0nOfNtdoIz2IPCftfqyYHe1nVaI"

### Sales Index
GET http://localhost:3000/sales.json

### Sales Create
POST http://localhost:3000/sales.json
Content-Type: application/json

{
"title": "test title",
"description": "test description",
"start_date": '2001-02-03T04:05:06+07:00', '%Y-%m-%dT%H:%M:%S%z',
"time": '2001-02-03T04:05:06+07:00', '%Y-%m-%dT%H:%M:%S%z',
"address": "test address",
"picture": "test url",
"end_date": '2001-02-03T04:05:06+07:00', '%Y-%m-%dT%H:%M:%S%z'
}

### Sales Show
GET http://localhost:3000/sales/1.json

### Sales Update
PATCH http://localhost:3000/sales/1.json
Content-Type: application/json

{
"title": "test title",
"description": "test description",
"start_date": 04/23/22,
"time": 14:00,
"address": "test address",
"picture": "test url",
"end_date": 04/23/22
}

### Sales Destroy
DELETE http://localhost:3000/sales/1.json

### Users create (signup)
POST http://localhost:3000/users

Content-Type: application/json

{
  "name": "April Powers",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create
POST http://localhost:3000/sessions
Content-Type: application/json

{"email": "test@test.com",
"password": "password"}