@jwt = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTEyODA5NDR9._ZUm3kbn3sh568Esr4r-8JqcrACmEhKPwj2K3JnvHh0"

### Sales Index
GET http://localhost:3000/sales.json

### Sales Create
POST http://localhost:3000/sales.json
Content-Type: application/json

{
"title": "test title",
"description": "test description",
"start_date": "2001-02-03",
"start_time": "04:05:06",
"address": "test address",
"picture": "test url",
"end_date": "2001-02-03",
"end_time": "04:05:06"
}

### Sales Show
GET http://localhost:3000/sales/1.json

### Sales Update
PATCH http://localhost:3000/sales/5.json
Content-Type: application/json

{
"title": "HUGE garage sale",
"description": "test description",
"start_date": "04-23-22",
"start_time": "07:00:00",
"address": "test address",
"picture": "test url",
"end_date": "04-23-22",
"end_time": "14:00:00"
}

### Sales Destroy
DELETE http://localhost:3000/sales/1.json

### Users create (signup)
POST http://localhost:3000/users

Content-Type: application/json

{
  "name": "April Powers",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create
POST http://localhost:3000/sessions
Content-Type: application/json

{"email": "test@test.com",
"password": "password"}